name: React app CI

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: environment
        required: true
        options:
          - dev
          - qa
          - pdn 
        default: get

jobs:
  build_app:
    name: compile the application
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: npm install 
      run: |
        npm install  

    - name: node install 
      uses: actions/setup-node@v3
      with:
        node-version: 22.x  

    - name: run build  
      run: |
        npm run build --if-present

    - name: run test 
      run: |
        npm test

    - name: upload compilation artifact
      uses: actions/upload-artifact@v3
      with:
        name: react-app-artifact
        retention-days: 30
        path: |
          build/*
               